language: android
sudo: false
android:
  components:
    - android-23
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
jdk:
  - oraclejdk8
script: ./gradlew testDebug
after_success: ./gradlew jacocoTestDebugUnitTestReport coveralls
