language: android
sudo: false
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-23
    - sys-img-armeabi-v7a-android-23
    - extra-android-m2repository
jdk:
  - oraclejdk8
script:
  - ./gradlew jacocoTestDebugUnitTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
