language: android
sudo: false
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-23
jdk:
  - oraclejdk8
script: ./gradlew testDebug
after_success: ./gradlew jacocoTestDebugUnitTestReport coveralls
