language: android
sudo: false
android:
  components:
    - android-22
    - build-tools-22.0.1
    - extra
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
jdk:
  - oraclejdk8
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script: ./gradlew testDebug connectedDebugAndroidTest
after_script: adb logcat

